#!/usr/bin/env bash
# generate-spec-index.sh — Deterministic regenerator for the three sentinel-bounded
# navigation zones (INDEX / PRS / BACKLINKS) inside every version-marked SPEC-MOC.md.
#
# Single shared, runtime-agnostic copy (FR-020) — sibling of reviewability-gate.sh /
# generate-pr-body.sh; consumed by speckit-status (--check) and speckit-autopilot
# (write mode) by path, never duplicated into codex-skills/.
#
# Usage:    generate-spec-index.sh [--check] [REPO_ROOT]
# Exit:     0 = current/clean   1 = stale (--check found drift)   2 = error
#
# Contracts (authoritative — this script matches them byte-for-byte):
#   specs/prsg-003-spec-index/contracts/generator-cli.md       (CLI + 3-way exit)
#   specs/prsg-003-spec-index/contracts/sentinel-grammar.md    (D1/D2 byte framing)
#   specs/prsg-003-spec-index/contracts/prs-manifest.schema.md (D3 PRS render)
#
# bash + jq only; no network, no gh — a pure function of committed files (SC-008).

set -euo pipefail

# ── Plugin root — derived from THIS script's path: scripts -> speckit-autopilot ->
# skills -> speckit-pro (three dirs up). Used for the REPO_ROOT default below.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

# Reused canonical libs (FR-004), co-located with the generator under scripts/lib/
# so they ship inside the plugin — the test tree (tests/speckit-pro/) does not ship.
# shellcheck source=lib/moc-id-normalize.sh
source "$SCRIPT_DIR/lib/moc-id-normalize.sh"
# shellcheck source=lib/moc-frontmatter.sh
source "$SCRIPT_DIR/lib/moc-frontmatter.sh"

# ── The six sentinel lines — defined ONCE, in one place (D1, FR-001). Matched by
# full-line string equality, never a loose substring regex, so a `GENERATED:` token
# in prose can never be mistaken for a sentinel. The template (FR-017) and the
# inject-if-missing path (FR-008) reproduce this exact framing => byte-identical.
readonly INDEX_START='<!-- GENERATED:INDEX:START (do not edit; regenerated by generate-spec-index.sh) -->'
readonly INDEX_END='<!-- GENERATED:INDEX:END -->'
readonly PRS_START='<!-- GENERATED:PRS:START (do not edit; regenerated by generate-spec-index.sh) -->'
readonly PRS_END='<!-- GENERATED:PRS:END -->'
readonly BACKLINKS_START='<!-- GENERATED:BACKLINKS:START (do not edit; regenerated by generate-spec-index.sh) -->'
readonly BACKLINKS_END='<!-- GENERATED:BACKLINKS:END -->'

# Plain-text PRS field separator: U+00B7 MIDDLE DOT (bytes 0xC2 0xB7), per D3 —
# NOT an ASCII dot, NOT a link.
readonly PRS_SEP=$'\xc2\xb7'

repo_structure_marker_current() {
  local marker="$REPO_ROOT/.specify/structure-version.json"
  [ -r "$marker" ] || return 1
  jq -e '(.structureVersion | type == "number") and (.structureVersion >= 1) and (.structureVersion == (.structureVersion | floor))' \
    "$marker" >/dev/null 2>&1
}

active_feature_rel() {
  local feature="$REPO_ROOT/.specify/feature.json"
  [ -r "$feature" ] || return 1
  jq -er '.feature_directory | select(type == "string" and length > 0)' \
    "$feature" 2>/dev/null || return 1
}

candidate_out_of_scope_reason() {
  local id="$1" first
  if [[ "$id" =~ ^[0-9]{4}($|-) ]]; then
    printf 'date_named_legacy_namespace'
    return 0
  fi
  first="${id%%-*}"
  if [[ "$first" =~ ^[A-Za-z]+$ ]] && [ "$first" != "prsg" ] && [ "$first" != "PRSG" ] && [ "$first" != "spec" ] && [ "$first" != "SPEC" ]; then
    printf 'non_speckit_namespace'
    return 0
  fi
  return 1
}

slugify_heading() {
  tr '[:upper:]' '[:lower:]' \
    | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//'
}

# ── Internal-error trap (T008): set -E so the ERR trap fires inside functions too;
# an unexpected `set -e` failure maps to an actionable stderr line + exit 2 (same
# discipline as the PRSG-002 lints). Disarmed (`trap - ERR EXIT`) immediately before
# any DELIBERATE non-zero exit so a `--check` stale `exit 1` is never remapped to 2.
set -E
# shellcheck disable=SC2329  # invoked indirectly via the ERR trap
_on_err() {
  local rc=$?
  trap - ERR EXIT
  printf 'generate-spec-index.sh: internal error (rc=%s) near %s:%s\n' \
    "$rc" "${BASH_SOURCE[1]:-?}" "${BASH_LINENO[0]:-?}" >&2
  exit 2
}
trap _on_err ERR

# err <message…> — actionable error to stderr, exit 2 (disarm first so the trap
# does not re-fire on the way out). Used for every deliberate fail-safe.
err() {
  trap - ERR EXIT
  printf 'generate-spec-index.sh: %s\n' "$*" >&2
  exit 2
}

# die2 — silent exit-2 fail-safe: same trap-disarm as err() but prints NOTHING.
# Used at call sites where the callee (e.g. render_prs) has ALREADY emitted the one
# precise, actionable stderr line; a second line here would muddy the single message
# a consumer (speckit-status) is told to surface. The `|| die2` is still load-bearing
# — `local x="$(…)"` / a bare assignment masks the failure under set -e, so the
# explicit propagation is required to reach exit 2 rather than wrongly continuing.
die2() {
  trap - ERR EXIT
  exit 2
}

# ── Argument parsing (T007): [--check] [REPO_ROOT], order-tolerant for the flag.
CHECK_MODE=0
REPO_ROOT=""
while [ $# -gt 0 ]; do
  case "$1" in
    --check) CHECK_MODE=1 ;;
    -h|--help)
      trap - ERR EXIT
      printf 'Usage: generate-spec-index.sh [--check] [REPO_ROOT]\n'
      exit 0
      ;;
    --*) err "unknown option: $1" ;;
    *)
      if [ -n "$REPO_ROOT" ]; then err "unexpected extra argument: $1"; fi
      REPO_ROOT="$1"
      ;;
  esac
  shift
done

# Default REPO_ROOT: the repository that contains the plugin (PLUGIN_ROOT's parent),
# so the generator is runnable in any consuming project (mirrors the PRSG-002 lints'
# optional scan-root arg). A fixture/consumer passes its own root positionally.
if [ -z "$REPO_ROOT" ]; then
  REPO_ROOT="$(cd "$PLUGIN_ROOT/.." && pwd)"
fi
[ -d "$REPO_ROOT" ] || err "REPO_ROOT is not a directory: $REPO_ROOT"

SPECS_DIR="$REPO_ROOT/specs"

# ─────────────────────────────────────────────────────────────────────────────
# Zone-body renderers
# ─────────────────────────────────────────────────────────────────────────────

# render_index <spec_dir> [is_home] — the roadmap INDEX zone (PRSG-004 FR-011).
# CONTEXT-SCOPED: render_index is invoked against every spec-MOC's present INDEX
# zone (where it MUST stay empty, FR-018) AND against the roadmap-MOC home note's
# INDEX zone (where it fills repo-wide). The 2nd arg defaults to 0, so the spec-MOC
# call site (3-arg rebuild_map -> render_index "$spec_dir") stays byte-identical to
# the pre-activation empty body. Only is_home=1 produces rows.
#
# When is_home=1 the body is the repo-wide index over every gated spec under
# $SPECS_DIR: one row `- [<spec_id>](../../../specs/<dir>/SPEC-MOC.md) · <status>`,
# normalized-ID ascending (FR-013), spec_id/status read from frontmatter (FR-012),
# rows whose spec_id is absent/empty skipped (FR-015a), empty status still emits a
# row with a blank status field (FR-015), the separator the U+00B7 PRS_SEP framing
# (FR-012/FR-014). A relative []() target, never a [[wikilink]] (SC-006). spec_dir
# is unused in the home-note path (the scan is repo-wide), kept for signature parity
# with the spec-MOC call. Link + status only — no table, no H1 parse (FR-022).
render_index() {
  local spec_dir="$1" is_home="${2:-0}"
  [ "$is_home" = 1 ] || return 0     # spec-MOC (default): empty, byte-identical

  # Repo-wide scan, LC_ALL=C sorted so enumeration order never leaks (SC-009).
  local sortable="" d moc spec_id status norm
  while IFS= read -r d; do
    [ -n "$d" ] || continue
    moc="$d/SPEC-MOC.md"
    [ -f "$moc" ] || continue
    moc_is_gated "$moc" || continue            # legacy/non-marked skipped (FR-016)
    # spec_id is the link text AND the sort key; absent/empty => skip (FR-015a).
    spec_id="$(moc_frontmatter_field "$moc" spec_id)" || continue
    [ -n "$spec_id" ] || continue
    # status is display-only; absent/empty still emits a row (FR-015).
    status="$(moc_frontmatter_field "$moc" status)" || status=""
    norm="$(moc_normalize "$spec_id")"
    # Sort key (col1) = normalized id; the rendered row (col2) follows. Sorting the
    # whole line is fully deterministic: normalized-id ascending, ties broken by the
    # row bytes. The link is relative docs/ai/specs -> repo-root specs (../../../).
    sortable+="$(printf '%s\t- [%s](../../../specs/%s/SPEC-MOC.md) %s %s' \
      "$norm" "$spec_id" "$(basename "$d")" "$PRS_SEP" "$status")"$'\n'
  done < <(find "$SPECS_DIR" -mindepth 1 -maxdepth 1 -type d | LC_ALL=C sort)

  if repo_structure_marker_current; then
    local active_rel="" active_base=""
    active_rel="$(active_feature_rel || true)"
    [ -n "$active_rel" ] && active_base="$(basename "$active_rel")"

    local branch reason target label
    while IFS= read -r d; do
      [ -n "$d" ] || continue
      branch="$(basename "$d")"
      moc="$d/SPEC-MOC.md"

      [ -f "$moc" ] && moc_is_gated "$moc" && continue
      reason="$(candidate_out_of_scope_reason "$branch" || true)"
      [ -z "$reason" ] || continue
      if [ -n "$active_base" ]; then
        if [ "specs/$branch" = "$active_rel" ] || moc_id_match "$active_base" "$branch"; then
          continue
        fi
      fi

      target="../../../specs/$branch/spec.md"
      label="$(printf '%s' "$branch" | tr '[:lower:]' '[:upper:]')"
      norm="$(moc_normalize "$branch")"
      sortable+="$(printf '%s\t- [%s](%s) %s %s' \
        "$norm" "$label" "$target" "$PRS_SEP" "")"$'\n'
    done < <(find "$SPECS_DIR" -mindepth 1 -maxdepth 1 -type d | LC_ALL=C sort)

    local memory="$REPO_ROOT/.specify/memory/spec.md"
    if [ -f "$memory" ]; then
      local heading slug
      while IFS= read -r heading; do
        heading="${heading### }"
        heading="${heading## }"
        [ -n "$heading" ] || continue
        slug="$(printf '%s' "$heading" | slugify_heading)"
        reason="$(candidate_out_of_scope_reason "$slug" || true)"
        [ -z "$reason" ] || continue
        norm="$(moc_normalize "$slug")"
        label="$(printf '%s' "${slug%%-*}-${slug#*-}" | tr '[:lower:]' '[:upper:]')"
        target="../../../.specify/memory/spec.md#$slug"
        sortable+="$(printf '%s\t- [%s](%s) %s %s' \
          "$norm" "$label" "$target" "$PRS_SEP" "")"$'\n'
      done < <(grep -E '^##[[:space:]]+' "$memory" 2>/dev/null || true)
    fi
  fi

  [ -n "$sortable" ] || return 0     # no gated specs => empty INDEX (not an error)

  # Emit rows in normalized-ID ascending order; drop the sort-key column. Sorting the
  # whole <norm>\t<row> line (no -k restriction) is deterministic: the leading <norm>
  # field orders the rows, and the row bytes break any normalized-id tie stably
  # (SC-004). The \t delimiter sorts before any printable row byte under LC_ALL=C.
  printf '%s' "$sortable" | LC_ALL=C sort | while IFS=$'\t' read -r _norm row; do
    [ -n "$row" ] || continue
    printf '%s\n' "$row"
  done
}

# render_prs <spec_dir> — plain-text PR rows from <spec_dir>/.process/prs.json
# (FR-010, D3). Never gh/network. Absent file OR records:[] => empty zone (FR-011).
# Malformed/unreadable => fail-safe exit 2 (FR-016), distinct from absent/empty.
# Rows: "<slice> · PR#<pr> · <merged_sha>", ordered by normalized slice asc then
# pr asc. Output: the rendered rows (may be empty) on stdout.
render_prs() {
  local spec_dir="$1"
  local manifest="$spec_dir/.process/prs.json"
  [ -e "$manifest" ] || return 0          # absent => empty-but-valid
  # On a fault, print an actionable stderr line and RETURN 1 (never exit). This
  # function runs inside command substitution, so the caller must turn the non-zero
  # return into the exit-2 fail-safe via `|| err …` — an exit here would only leave
  # the $() subshell and be swallowed.
  if [ ! -r "$manifest" ]; then
    printf 'generate-spec-index.sh: unreadable PRS manifest: %s\n' "$manifest" >&2
    return 1
  fi

  # Validate JSON shape with jq; a parse/shape failure is the malformed case.
  if ! jq -e 'has("records") and (.records | type == "array")' "$manifest" >/dev/null 2>&1; then
    printf 'generate-spec-index.sh: malformed PRS manifest (invalid JSON or missing records[]): %s\n' "$manifest" >&2
    return 1
  fi

  local schema_version
  if ! jq -e '
    if has("schemaVersion") then
      (.schemaVersion | type == "number" and . == floor)
    else
      true
    end
  ' "$manifest" >/dev/null 2>&1; then
    printf 'generate-spec-index.sh: malformed PRS manifest (schemaVersion must be an integer): %s\n' "$manifest" >&2
    return 1
  fi
  if ! schema_version="$(jq -r 'if has("schemaVersion") then .schemaVersion else 1 end' "$manifest" 2>/dev/null)"; then
    printf 'generate-spec-index.sh: malformed PRS manifest (invalid schemaVersion): %s\n' "$manifest" >&2
    return 1
  fi

  if [ "$schema_version" = "2" ]; then
    local v2_rows
    if ! v2_rows="$(
      jq -r '
        def req_string($name):
          if ((.[$name] | type) == "string" and (.[$name] | length) > 0) then .[$name] else error($name) end;
        def req_int($name):
          if ((.[$name] | type) == "number" and .[$name] == (.[$name] | floor)) then .[$name] else error($name) end;
        .records
        | sort_by(.review_order, .slice_id)
        | .[]
        | . as $row
        | (req_int("review_order") | tostring) as $order
        | req_string("slice_id") as $slice
        | (if (.pr_number == null) then "pending"
           elif ((.pr_number | type) == "number" and .pr_number == (.pr_number | floor)) then "PR#" + (.pr_number | tostring)
           else error("pr_number") end) as $pr
        | req_string("status") as $status
        | req_string("branch") as $branch
        | req_string("base_branch") as $base
        | (if (.status == "merged" and (.merged_sha | type) == "string" and (.merged_sha | length) > 0)
           then .merged_sha
           else req_string("head_sha")
           end) as $sha
        | (if (.declared_files | type) == "array" then (.declared_files | join(", ")) else error("declared_files") end) as $scope
        | req_string("verification_evidence") as $verification
        | [$order, $slice, $pr, $status, $branch, $base, $sha, $scope, $verification]
        | @tsv
      ' "$manifest" 2>/dev/null
    )"; then
      printf 'generate-spec-index.sh: malformed PRS manifest (schemaVersion 2 record missing/wrong-typed field): %s\n' "$manifest" >&2
      return 1
    fi

    [ -n "$v2_rows" ] || return 0
    printf '| Order | Slice | PR | Status | Branch | Base | SHA | Scope | Verification |\n'
    printf '|---|---|---|---|---|---|---|---|---|\n'
    while IFS=$'\t' read -r order slice pr status branch base sha scope verification; do
      [ -n "$order" ] || continue
      printf '| %s | %s | %s | %s | %s | %s | %s | %s | %s |\n' \
        "$order" "$slice" "$pr" "$status" "$branch" "$base" "$sha" "$scope" "$verification"
    done <<<"$v2_rows"
    return 0
  fi

  if [ "$schema_version" != "1" ]; then
    printf 'generate-spec-index.sh: malformed PRS manifest (unsupported schemaVersion "%s"): %s\n' "$schema_version" "$manifest" >&2
    return 1
  fi

  # Emit tab-separated "<slice>\t<pr>\t<merged_sha>" rows. Each record must satisfy
  # the schema (prs-manifest.schema.md): slice string, pr INTEGER, merged_sha string.
  # A missing field OR a wrong type (e.g. "pr":"abc" or "pr":117.5) is the malformed
  # case — jq raises error(), the `if !` turns it into the fail-safe via the caller's
  # `|| err`. Presence alone is not enough: a string/float pr would survive a
  # presence-only guard and then corrupt the printf %d below.
  local rows
  if ! rows="$(
    jq -r '
      .records[]
      | if ((.slice | type) == "string")
           and ((.pr | type) == "number") and (.pr == (.pr | floor))
           and ((.merged_sha | type) == "string") then
          [ (.slice | tostring), (.pr | tostring), (.merged_sha | tostring) ] | @tsv
        else
          error("record has a missing or wrong-typed field (slice/pr/merged_sha)")
        end
    ' "$manifest" 2>/dev/null
  )"; then
    printf 'generate-spec-index.sh: malformed PRS manifest (record missing/wrong-typed slice/pr/merged_sha): %s\n' "$manifest" >&2
    return 1
  fi

  [ -n "$rows" ] || return 0              # records:[] => empty-but-valid

  # Build sortable lines: <norm-slice>\t<zero-padded-pr>\t<slice>\t<pr>\t<sha>.
  # The jq guard above already enforces an integer pr; this bash guard is
  # belt-and-suspenders so the `printf %012d` can never hit an invalid number
  # (defense in depth — a corrupt row must fail safe, never write).
  local sortable="" slice pr sha norm
  while IFS=$'\t' read -r slice pr sha; do
    [ -n "$slice" ] || continue
    case "$pr" in
      ''|*[!0-9]*)
        printf 'generate-spec-index.sh: malformed PRS manifest (non-integer pr "%s"): %s\n' "$pr" "$manifest" >&2
        return 1 ;;
    esac
    norm="$(moc_normalize "$slice")"
    # One newline per record from the $'\n' append; the printf format carries no
    # trailing \n (a $()-wrapped printf newline would be stripped anyway). Output is
    # byte-identical to the prior form — the $() stripped one of the two newlines.
    sortable+="$(printf '%s\t%012d\t%s\t%s\t%s' "$norm" "$pr" "$slice" "$pr" "$sha")"$'\n'
  done <<<"$rows"

  # Sort by normalized slice (col1) asc then padded pr (col2) asc, then render.
  printf '%s' "$sortable" | LC_ALL=C sort -t$'\t' -k1,1 -k2,2 | while IFS=$'\t' read -r _norm _pad slice pr sha; do
    [ -n "$slice" ] || continue
    printf '%s %s PR#%s %s %s\n' "$slice" "$PRS_SEP" "$pr" "$PRS_SEP" "$sha"
  done
}

# render_backlinks <spec_dir> <branch> — relative reachability links to that spec's
# OWN on-disk artifacts (FR-006/FR-018), relative to the MOC's own directory.
# Excludes SPEC-MOC.md itself (it is the map note, never its own backlink). Fixed
# artifact precedence then lexicographic path within each bucket (FR-005, SC-002);
# only files that exist on disk (no dangling links). Output: "- [path](path)" lines.
render_backlinks() {
  local spec_dir="$1"
  # All regular files under the spec dir, path RELATIVE to spec_dir, LC_ALL=C sorted
  # so enumeration order never leaks (SC-009). Exclude the map note itself.
  local all
  all="$(cd "$spec_dir" && find . -type f | sed 's#^\./##' | LC_ALL=C sort)"

  local rel
  # Bucket each file by the fixed precedence; emit buckets in order, lexicographic
  # within each. A file matches at most one bucket; later buckets exclude earlier.
  # Collect per-bucket lists in precedence order; newline-delimited accumulation.
  local b_spec="" b_plan="" b_tasks="" b_data="" b_research="" b_contracts="" b_checklists="" b_process="" b_other=""
  while IFS= read -r rel; do
    [ -n "$rel" ] || continue
    case "$rel" in
      SPEC-MOC.md) continue ;;                       # the map note is not its own link
      spec.md)            b_spec+="$rel"$'\n' ;;
      plan.md)            b_plan+="$rel"$'\n' ;;
      tasks.md)           b_tasks+="$rel"$'\n' ;;
      data-model.*)       b_data+="$rel"$'\n' ;;
      research.*)         b_research+="$rel"$'\n' ;;
      contracts/*)        b_contracts+="$rel"$'\n' ;;
      checklists/*)       b_checklists+="$rel"$'\n' ;;
      .process/*)         b_process+="$rel"$'\n' ;;
      *)                  b_other+="$rel"$'\n' ;;
    esac
  done <<<"$all"

  # Render in fixed precedence; `.process` last among named buckets, then anything
  # else (lexicographic) so no on-disk artifact is silently dropped.
  local bucket
  for bucket in "$b_spec" "$b_plan" "$b_tasks" "$b_data" "$b_research" "$b_contracts" "$b_checklists" "$b_process" "$b_other"; do
    [ -n "$bucket" ] || continue
    while IFS= read -r rel; do
      [ -n "$rel" ] || continue
      printf -- '- [%s](%s)\n' "$rel" "$rel"
    done <<<"$bucket"
  done
}

# ─────────────────────────────────────────────────────────────────────────────
# Zone assembly (T010) — the SINGLE block builder shared by template-fill and
# inject-if-missing so a template-born map and an injection-migrated map are
# byte-identical (FR-008/FR-017, D2). Emits, with exact framing:
#   <INDEX_START>\n[body]\n<INDEX_END>\n\n<PRS_START>\n[body]\n<PRS_END>\n\n
#   <BACKLINKS_START>\n[body]\n<BACKLINKS_END>\n
# An empty zone is START then END on consecutive lines (no blank, no body).
# stdout has NO leading/trailing blank line of its own; the caller frames it with
# exactly one blank line before INDEX_START.
# ─────────────────────────────────────────────────────────────────────────────
assemble_zone_block() {
  local idx="$1" prs="$2" bl="$3"
  # Between zones: "\n\n" = newline that terminates the END line + one blank line
  # separator (D2 rule 3). After the final BACKLINKS:END: a single "\n" (D2 rule 4).
  _emit_zone "$INDEX_START" "$INDEX_END" "$idx"
  printf '\n\n'
  _emit_zone "$PRS_START" "$PRS_END" "$prs"
  printf '\n\n'
  _emit_zone "$BACKLINKS_START" "$BACKLINKS_END" "$bl"
  printf '\n'
}

# _emit_zone <start-line> <end-line> <body> — one zone with D2 framing. Empty body
# => START then END on consecutive lines, no blank between (link-free empty zone).
# The END line has NO trailing newline of its own; the caller frames it.
_emit_zone() {
  local start="$1" end="$2" body="$3"
  printf '%s\n' "$start"
  if [ -n "$body" ]; then
    printf '%s\n' "$body"
  fi
  printf '%s' "$end"
}

# ─────────────────────────────────────────────────────────────────────────────
# Marker accounting + per-map regeneration
# ─────────────────────────────────────────────────────────────────────────────

# _count_lines <needle> <file> — exact full-line-equality count of <needle> in
# <file>. grep -F -x is anchored to the whole line, so a `GENERATED:` token in
# prose can never match a sentinel (D1). Guarded for set -e (no match => 0).
_count_lines() {
  local needle="$1" file="$2"
  grep -Fxc -- "$needle" "$file" 2>/dev/null || true
}

# rebuild_map <moc> <spec_dir> <branch> — produce the freshly regenerated full
# file body for one MOC on stdout. Validates marker balance (FR-022 fail-safe):
# each kind must have an equal, ∈{0,1} START/END count. Whole-zone replace of each
# present pair (FR-002); inject the three empty-then-filled zones only when ALL
# three pairs are absent (FR-008); a present-but-partial/duplicated pair => exit 2.
# _zone_state <start-count> <end-count> — classify one zone's marker pair. Echoes
# `present` (1 START + 1 END) or `absent` (0 + 0). Returns 1 for anything else
# (duplicated START, orphan END, START-without-END) — the unbalanced fail-safe,
# which the caller turns into an exit-2 with an actionable message. No err()/exit
# inside this command-substituted helper (that would only exit its own subshell).
_zone_state() {
  local s="$1" e="$2"
  if [ "$s" = "1" ] && [ "$e" = "1" ]; then printf 'present'; return 0
  elif [ "$s" = "0" ] && [ "$e" = "0" ]; then printf 'absent'; return 0
  else return 1
  fi
}

# rebuild_map <moc> <spec_dir> <branch> — emit the freshly regenerated full file
# body for one MOC on stdout. Marker validation + the malformed-PRS check run here
# (directly in this function, so an err()/exit propagates out as this function's —
# and its command substitution's — exit 2, which the caller captures). Whole-zone
# replace of each present pair (FR-002); inject the three zones only when ALL three
# pairs are absent (FR-008); a partial/duplicated pair => fail-safe exit 2 (FR-022).
rebuild_map() {
  local moc="$1" spec_dir="$2" branch="$3" is_home="${4:-0}"

  # Marker counts per kind (full-line equality — prose can't masquerade, D1).
  local is ie ps pe bs be
  is="$(_count_lines "$INDEX_START" "$moc")"
  ie="$(_count_lines "$INDEX_END" "$moc")"
  ps="$(_count_lines "$PRS_START" "$moc")"
  pe="$(_count_lines "$PRS_END" "$moc")"
  bs="$(_count_lines "$BACKLINKS_START" "$moc")"
  be="$(_count_lines "$BACKLINKS_END" "$moc")"

  # Classify each kind; a non-{present,absent} classification is unbalanced => fail
  # safe with one actionable line (err disarms the trap, so no double-report).
  local st_index st_prs st_backlinks
  st_index="$(_zone_state "$is" "$ie")"     || err "unbalanced GENERATED:INDEX marker pair in: $moc"
  st_prs="$(_zone_state "$ps" "$pe")"       || err "unbalanced GENERATED:PRS marker pair in: $moc"
  st_backlinks="$(_zone_state "$bs" "$be")" || err "unbalanced GENERATED:BACKLINKS marker pair in: $moc"

  # Render the body of each present zone up front. render_prs returns non-zero on a
  # malformed manifest, having already printed the one precise stderr line naming the
  # offending prs.json; the `|| die2` propagates that into the exit-2 fail-safe
  # WITHOUT printing a second, less-precise line. The `||` is load-bearing — a bare
  # assignment masks the failure under set -e. Init to empty so an absent zone's var
  # is defined under set -u.
  local idx_body="" prs_body="" bl_body=""
  if [ "$st_index" = present ];     then idx_body="$(render_index "$spec_dir" "$is_home")"; fi
  if [ "$st_prs" = present ];       then prs_body="$(render_prs "$spec_dir")" || die2; fi
  if [ "$st_backlinks" = present ]; then bl_body="$(render_backlinks "$spec_dir")"; fi

  # FR-017a fail-safe: a home-note target with ALL three pairs absent is a MALFORMED
  # home note (a gated home note must carry its INDEX pair — FR-002), NOT a fresh
  # spec-MOC awaiting injection. It MUST NOT take the inject-if-missing path below
  # (which would inject all three zones and render PRS/BACKLINKS against the home
  # note's non-spec directory). Fail safe: exit 2, no write, naming the home note.
  if [ "$is_home" = 1 ] && [ "$st_index" = absent ] && [ "$st_prs" = absent ] && [ "$st_backlinks" = absent ]; then
    err "roadmap-MOC home note is gated but missing its GENERATED:INDEX zone: $moc"
  fi

  # Inject-if-missing: ONLY when all three pairs are absent. A map missing exactly
  # one pair (skip-one) keeps that zone absent — never injected (FR-009).
  if [ "$st_index" = absent ] && [ "$st_prs" = absent ] && [ "$st_backlinks" = absent ]; then
    # For an all-absent in-scope map, the PRS body was not rendered above (st_prs is
    # absent), so render it now — the injected zones must be filled too. `|| die2`:
    # render_prs already emitted the precise stderr line; propagate to exit 2 silently.
    prs_body="$(render_prs "$spec_dir")" || die2
    bl_body="$(render_backlinks "$spec_dir")"
    # Append the three-zone block at the canonical anchor (end of body) with exactly
    # one blank line before INDEX_START and a single trailing newline.
    local body
    body="$(_strip_trailing_blanks "$moc")"
    printf '%s\n\n' "$body"
    assemble_zone_block "$idx_body" "$prs_body" "$bl_body"
    return 0
  fi

  # Otherwise: stream the file, replacing the body of each PRESENT zone in place
  # (preserving existing positions + framing) and leaving absent zones untouched.
  _rewrite_present_zones "$moc" "$idx_body" "$prs_body" "$bl_body"
}

# _strip_trailing_blanks <file> — print file contents with the trailing run of
# blank/whitespace-only lines removed, so the inject anchor is exactly the end of
# the real body. Pure bash (portable; avoids BSD/GNU sed label-syntax divergence).
# $(cat) already drops the final newline run; then peel any whitespace-only trailing
# lines one at a time until the last line carries real content.
_strip_trailing_blanks() {
  local content last
  content="$(cat "$1")"
  while [ -n "$content" ]; do
    last="${content##*$'\n'}"                  # text after the final newline
    case "$last" in
      *[![:space:]]*) break ;;                 # last line has real content — stop
    esac
    if [ "$last" = "$content" ]; then
      content=""                               # single blank line, no newline left
    else
      content="${content%$'\n'*}"              # drop the trailing blank line
    fi
  done
  printf '%s' "$content"
}

# _rewrite_present_zones <file> <idx_body> <prs_body> <bl_body> — stream the file;
# for each present START..END block substitute the freshly rendered body. Lines
# outside any zone pass through verbatim. The END line keeps its own newline, so an
# empty zone renders START\nEND and a filled zone renders START\n<body>\nEND. Emits
# the file with its single trailing newline preserved.
_rewrite_present_zones() {
  local file="$1" idx_body="$2" prs_body="$3" bl_body="$4"
  local line in_zone="" out=""
  while IFS= read -r line || [ -n "$line" ]; do
    if [ -z "$in_zone" ]; then
      case "$line" in
        "$INDEX_START")     out+="$line"$'\n'; [ -n "$idx_body" ] && out+="$idx_body"$'\n'; in_zone="index" ;;
        "$PRS_START")       out+="$line"$'\n'; [ -n "$prs_body" ] && out+="$prs_body"$'\n'; in_zone="prs" ;;
        "$BACKLINKS_START") out+="$line"$'\n'; [ -n "$bl_body" ]  && out+="$bl_body"$'\n';  in_zone="backlinks" ;;
        *)                  out+="$line"$'\n' ;;
      esac
    else
      # Inside a zone: drop stale body lines until the matching END, then emit it.
      case "$in_zone:$line" in
        "index:$INDEX_END"|"prs:$PRS_END"|"backlinks:$BACKLINKS_END")
          out+="$line"$'\n'; in_zone="" ;;
        *) : ;;  # discard stale body line
      esac
    fi
  done <"$file"
  printf '%s' "$out"
}

# ─────────────────────────────────────────────────────────────────────────────
# Driver: discover in-scope maps, regenerate, diff (--check) or write (T009/T014)
# ─────────────────────────────────────────────────────────────────────────────
main() {
  # No specs/ tree => clean no-op success (SC-012).
  if [ ! -d "$SPECS_DIR" ]; then
    printf 'spec-index: no specs/ directory under %s — nothing to do.\n' "$REPO_ROOT"
    return 0
  fi

  # Discover spec dirs, LC_ALL=C sorted so processing order never leaks (SC-009).
  local spec_dirs=()
  local d
  while IFS= read -r d; do
    [ -n "$d" ] || continue
    spec_dirs+=("$d")
  done < <(find "$SPECS_DIR" -mindepth 1 -maxdepth 1 -type d | LC_ALL=C sort)

  # PASS 1 — select in-scope maps and regenerate each into memory. Validation
  # (marker balance, malformed PRS, non-regular-file target) happens HERE, before
  # any write, so a poison map aborts the whole batch with no partial write (D6).
  local in_moc=() in_new=() in_branch=()
  for d in "${spec_dirs[@]}"; do
    local branch moc
    branch="$(basename "$d")"
    moc="$d/SPEC-MOC.md"

    # A non-regular-file target where a MOC is expected is an error: a directory, a
    # symlink (even one resolving to a regular file — a naive `mv -f` would clobber
    # the link), or a broken symlink. `-e`/`-f` follow symlinks, so test `-L` FIRST
    # (it does not follow) before the follow-through `-e && ! -f` check. A spec dir
    # with no SPEC-MOC.md at all is simply not a map (skipped). [FR-016]
    if [ -L "$moc" ] || { [ -e "$moc" ] && [ ! -f "$moc" ]; }; then
      err "SPEC-MOC.md is not a regular file: $moc"
    fi
    [ -f "$moc" ] || continue

    # In scope iff version-marked (moc_is_gated). Legacy/non-marked => skip,
    # unmodified (FR-007, SC-007).
    if ! moc_is_gated "$moc"; then
      continue
    fi

    # Regenerate into memory. rebuild_map (and the renderers it calls) emit their
    # own actionable stderr line + exit 2 on a fail-safe (unbalanced markers,
    # malformed PRS). Because that runs inside this command substitution, capture
    # its rc explicitly and re-raise CLEANLY — disarm our trap first so the parent
    # never double-reports or remaps a child's exit 2 into a second error line.
    local new rc=0
    new="$(rebuild_map "$moc" "$d" "$branch")" || rc=$?
    if [ "$rc" -ne 0 ]; then
      trap - ERR EXIT
      exit 2
    fi
    in_moc+=("$moc")
    in_new+=("$new")
    in_branch+=("$branch")
  done

  # PASS 1b — discover roadmap-MOC home notes (FR-017), DISJOINT from the specs/
  # scan above (the docs/ai/specs/ tree does not overlap specs/). Glob is the
  # filename `docs/ai/specs/*-roadmap-MOC.md` (0..N). Each is gated via moc_is_gated;
  # a non-gated/legacy home note is skipped (not an error). A gated home note is
  # folded into the SAME in_moc/in_new/in_branch arrays but regenerated with
  # is_home=1 so render_index fills its INDEX repo-wide. Validation (the FR-017a
  # missing-INDEX fail-safe, marker balance) runs HERE in PASS 1, before any PASS 2
  # write, so a malformed home note aborts the whole batch with no partial write.
  local home_dir="$REPO_ROOT/docs/ai/specs"
  if [ -d "$home_dir" ]; then
    local hn
    while IFS= read -r hn; do
      [ -n "$hn" ] || continue
      local hlabel
      hlabel="$(basename "$hn")"

      # Same non-regular-file guard as the spec-MOC path: reject a symlink or a
      # non-regular target (test -L first; it does not follow), FR-016.
      if [ -L "$hn" ] || { [ -e "$hn" ] && [ ! -f "$hn" ]; }; then
        err "roadmap-MOC home note is not a regular file: $hn"
      fi
      [ -f "$hn" ] || continue

      # In scope iff version-marked. Legacy/non-gated home note => skip, unmodified.
      if ! moc_is_gated "$hn"; then
        continue
      fi

      # Regenerate with is_home=1. rebuild_map fails safe (its own stderr line +
      # exit 2) on the FR-017a missing-INDEX case or an unbalanced pair; capture the
      # rc from the command substitution and re-raise cleanly (disarm first).
      local hnew hrc=0
      hnew="$(rebuild_map "$hn" "$home_dir" "$hlabel" 1)" || hrc=$?
      if [ "$hrc" -ne 0 ]; then
        trap - ERR EXIT
        exit 2
      fi
      in_moc+=("$hn")
      in_new+=("$hnew")
      in_branch+=("$hlabel")
    done < <(find "$home_dir" -mindepth 1 -maxdepth 1 -name '*-roadmap-MOC.md' | LC_ALL=C sort)
  fi

  # PASS 2 — compare each regenerated body to the committed file. In --check mode
  # report drift and write nothing; in write mode write changed files atomically.
  local stale=0 wrote=0 i
  local n=${#in_moc[@]}
  for (( i = 0; i < n; i++ )); do
    local moc="${in_moc[$i]}" new="${in_new[$i]}" branch="${in_branch[$i]}"
    local old
    old="$(cat "$moc")"
    # Both `old` and `new` are command-substitution-captured, so each has had its
    # trailing newline run stripped identically. A committed map ends in exactly one
    # newline, so this body-vs-body equality is exact. The write re-adds the single
    # trailing newline (D2 rule 4), so a written-then-reread map compares equal =>
    # a second run is a zero-byte diff (SC-001).
    if [ "$old" = "$new" ]; then
      continue   # current — no change for this map
    fi

    stale=1
    if [ "$CHECK_MODE" -eq 1 ]; then
      printf 'spec-index: STALE — %s (regenerated zones differ from committed)\n' "$branch"
    else
      _atomic_write "$moc" "$new"
      wrote=$((wrote + 1))
      printf 'spec-index: regenerated %s\n' "$branch"
    fi
  done

  if [ "$CHECK_MODE" -eq 1 ]; then
    if [ "$stale" -eq 1 ]; then
      trap - ERR EXIT          # deliberate stale exit — never remap to error 2
      exit 1
    fi
    printf 'spec-index: index current — all in-scope maps up to date.\n'
    return 0
  fi

  if [ "$wrote" -eq 0 ]; then
    printf 'spec-index: index current — no maps needed regenerating.\n'
  fi
  return 0
}

# _atomic_write <target> <content> — write <content> to a sibling mktemp file then
# mv-rename over <target> (per-target atomicity, D6/FR-016): a failure on one map
# cannot half-write another, and a reader never sees a partial file. The temp file
# lives in the target's own directory so the mv is a same-filesystem atomic rename.
_atomic_write() {
  local target="$1" content="$2"
  local dir tmp
  dir="$(dirname "$target")"
  tmp="$(mktemp "$dir/.spec-index.XXXXXX")" || err "could not create temp file in $dir"
  # Re-add the single trailing newline that command substitution stripped from
  # $content, so every written map ends in exactly one \n (D2 rule 4).
  printf '%s\n' "$content" >"$tmp" || { rm -f "$tmp"; err "write failed for $target"; }
  mv -f "$tmp" "$target" || { rm -f "$tmp"; err "rename failed for $target"; }
}

main
# Clean exit (disarm the EXIT/ERR trap on the success path).
trap - ERR EXIT
exit 0
