#!/usr/bin/env python3
import subprocess, sys
child = subprocess.Popen([sys.executable, '-c', "import signal,time; signal.signal(signal.SIGTERM, signal.SIG_IGN); print('ready', flush=True); time.sleep(30)"], stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
assert child.stdout.readline() == b'ready\n'
print('child=' + str(child.pid), flush=True)
