#!/usr/bin/env bash
# test-relocate-process-artifacts.sh - Layer 4 RED fixtures for PRSG-011 Tier-2 relocation.

set -euo pipefail

source "$(dirname "$0")/../lib/assertions.sh"

PLUGIN_ROOT="$(cd "$(dirname "$0")/../../../speckit-pro" && pwd)"
SCRIPT="$PLUGIN_ROOT/skills/speckit-autopilot/scripts/relocate-process-artifacts.sh"

FIXTURE_DIR=$(mktemp -d)
FIXTURE_DIR="$(cd "$FIXTURE_DIR" && pwd -P)"
trap 'rm -rf "$FIXTURE_DIR"' EXIT

json_check() {
  local json="$1" expr="$2" msg="$3"
  local file="$FIXTURE_DIR/json-check.json"
  printf '%s' "$json" > "$file"
  if python3 - "$file" "$expr" >/dev/null 2>&1 <<'PY'
import json
import sys

with open(sys.argv[1], encoding="utf-8") as fh:
    data = json.load(fh)

expr = sys.argv[2]
safe_builtins = {"any": any, "all": all, "len": len, "list": list, "sorted": sorted}
if not eval(expr, {"__builtins__": safe_builtins}, {"data": data}):
    raise SystemExit(1)
PY
  then
    _pass
  else
    _fail "$msg"
  fi
}

assert_compact_json_object() {
  local json="$1"
  if printf '%s' "$json" | python3 -c 'import json, sys; data=json.load(sys.stdin); sys.exit(0 if isinstance(data, dict) else 1)' >/dev/null 2>&1 \
    && [[ "$json" != *$'\n'* ]]; then
    _pass
  else
    _fail "expected one compact JSON object on stdout"
  fi
}

assert_dir_exists() {
  local path="$1" msg="${2:-}"
  if [ -d "$path" ]; then
    _pass
  else
    _fail "${msg:+$msg: }directory not found: $path"
  fi
}

make_relocation_repo() {
  local repo="$1"
  local spec="$repo/specs/prsg-011-legacy"

  mkdir -p "$spec/contracts" "$spec/checklists" "$spec/evidence" "$spec/.process" "$repo/docs/ai/specs/.process"
  git -C "$repo" init -q
  git -C "$repo" config user.email support@openai.com
  git -C "$repo" config user.name Test
  git -C "$repo" config commit.gpgsign false

  cat > "$spec/SPEC-MOC.md" <<'EOF'
---
spec_id: PRSG-011
up: ../../docs/ai/specs/pr-size-governance-technical-roadmap.md
---

# PRSG-011 Legacy Map

<!-- GENERATED:INDEX:START (do not edit; regenerated by generate-spec-index.sh) -->
<!-- GENERATED:INDEX:END -->
EOF
  printf '# Spec\n' > "$spec/spec.md"
  printf '# Plan\n' > "$spec/plan.md"
  printf '# Tasks\n' > "$spec/tasks.md"
  printf '# Research\n' > "$spec/research.md"
  printf '# Data Model\n' > "$spec/data-model.md"
  printf '# Quickstart\n' > "$spec/quickstart.md"
  printf '# Contract Analysis Must Stay Visible\n' > "$spec/contracts/analysis.md"
  printf '# Checklist Report Must Stay Visible\n' > "$spec/checklists/cleanup-report.md"

  printf '# Retrospective\n' > "$spec/retrospective.md"
  printf '# Analysis\n' > "$spec/analysis.md"
  printf '# Cleanup\n' > "$spec/cleanup-report.md"
  printf '# Incident Report\n' > "$spec/incident-report.md"
  printf '# UAT Notes\n' > "$spec/uat-notes.md"
  printf '# Design Concept\n' > "$spec/design-concept.md"
  printf '# Workflow\n' > "$spec/workflow.md"
  printf '# Unrelated Notes\n' > "$spec/notes.md"
  printf '# Peer Review\n' > "$spec/peer-review-round1.md"
  printf 'evidence from root evidence dir\n' > "$spec/evidence/verification-evidence.md"
  printf 'supporting evidence stays with evidence dir\n' > "$spec/evidence/supporting-note.md"
  printf '# Existing UAT\n' > "$spec/.process/uat-runbook.md"
  printf '# Already Normalized Report\n' > "$spec/.process/existing-report.md"

  printf '# Design Concept\n' > "$repo/docs/ai/specs/prsg-011-legacy-design-concept.md"
  printf '# Workflow\n' > "$repo/docs/ai/specs/prsg-011-legacy-workflow.md"
  printf '# Deferred PRSG-001 Design Concept\n' > "$repo/docs/ai/specs/PRSG-001-design-concept.md"
  printf '# Deferred PRSG-001 Workflow\n' > "$repo/docs/ai/specs/PRSG-001-workflow.md"
  printf '# Existing Docs Process\n' > "$repo/docs/ai/specs/.process/existing-process-note.md"
  printf '# Unrelated Roadmap\n' > "$repo/docs/ai/specs/pr-size-governance-technical-roadmap.md"

  git -C "$repo" add .
  git -C "$repo" commit -qm "seed relocation fixture"
}

commit_fixture_change() {
  local repo="$1" msg="$2"
  git -C "$repo" add -A
  git -C "$repo" commit -qm "$msg"
}

run_relocator() {
  local out_var="$1" err_var="$2"
  shift 2
  local stdout_file="$FIXTURE_DIR/stdout.$RANDOM"
  local stderr_file="$FIXTURE_DIR/stderr.$RANDOM"
  local rc=0
  "$@" >"$stdout_file" 2>"$stderr_file" || rc=$?
  printf -v "$out_var" '%s' "$(cat "$stdout_file")"
  printf -v "$err_var" '%s' "$(cat "$stderr_file")"
  return "$rc"
}

section "Tier-2 script presence"

set_test "relocate-process-artifacts.sh exists"
assert_file_exists "$SCRIPT"

set_test "relocate-process-artifacts.sh is executable"
assert_file_executable "$SCRIPT"

section "dry-run shared JSON report and backup planning"

repo="$FIXTURE_DIR/repo-dry-run"
mkdir -p "$repo"
make_relocation_repo "$repo"
backup_root="$FIXTURE_DIR/backups-dry-run"
backup_stamp="20260608T000000Z"
expected_backup="$backup_root/speckit-migration-backup-$backup_stamp"

set_test "dry-run exits 0"
result=0
run_relocator output stderr_output \
  env SPECKIT_MIGRATION_BACKUP_ROOT="$backup_root" SPECKIT_MIGRATION_BACKUP_STAMP="$backup_stamp" \
  "$SCRIPT" --dry-run --spec specs/prsg-011-legacy --repo-root "$repo" || result=$?
assert_eq "0" "$result" "exit code"

set_test "dry-run emits no stderr on success"
assert_eq "" "$stderr_output" "stderr"

set_test "dry-run emits one compact JSON object"
assert_compact_json_object "$output"

set_test "dry-run report uses the shared key order"
json_check "$output" \
  "list(data.keys()) == ['schema_version', 'script', 'mode', 'repo_root', 'spec_dir', 'active_feature', 'dirty_tree', 'backup', 'status', 'items', 'recovery']" \
  "shared migration report key order"

set_test "dry-run report identifies the relocate script"
assert_json_field "$output" "script" "relocate-process-artifacts"

set_test "dry-run report records mode"
assert_json_field "$output" "mode" "dry-run"

set_test "dry-run report records repo root"
assert_json_field "$output" "repo_root" "$repo"

set_test "dry-run report records repo-relative spec dir"
assert_json_field "$output" "spec_dir" "specs/prsg-011-legacy"

set_test "dry-run report uses schema version 1"
assert_json_field "$output" "schema_version" "1"

set_test "dry-run reports absent active feature as non-blocking"
assert_json_field "$output" "active_feature.state" "absent"

set_test "dry-run reports pending status for relocatable work"
assert_json_field "$output" "status" "pending"

set_test "dry-run uses deterministic backup override path"
assert_json_field "$output" "backup.path" "$expected_backup"

set_test "dry-run does not create the planned backup"
assert_file_not_exists "$expected_backup"

set_test "dry-run marks backup as not created"
assert_json_field "$output" "backup.created" "False"

set_test "dry-run includes spec-root PROCESS move"
json_check "$output" \
  "any(i.get('action') == 'move' and i.get('source') == 'specs/prsg-011-legacy/retrospective.md' and i.get('target') == 'specs/prsg-011-legacy/.process/retrospective.md' for i in data['items'])" \
  "missing retrospective.md move item"

set_test "dry-run includes every root PROCESS allow-list family"
json_check "$output" \
  "('specs/prsg-011-legacy/analysis.md', 'specs/prsg-011-legacy/.process/analysis.md') in [(i.get('source'), i.get('target')) for i in data['items'] if i.get('action') == 'move'] and ('specs/prsg-011-legacy/cleanup-report.md', 'specs/prsg-011-legacy/.process/cleanup-report.md') in [(i.get('source'), i.get('target')) for i in data['items'] if i.get('action') == 'move'] and ('specs/prsg-011-legacy/incident-report.md', 'specs/prsg-011-legacy/.process/incident-report.md') in [(i.get('source'), i.get('target')) for i in data['items'] if i.get('action') == 'move'] and ('specs/prsg-011-legacy/uat-notes.md', 'specs/prsg-011-legacy/.process/uat-notes.md') in [(i.get('source'), i.get('target')) for i in data['items'] if i.get('action') == 'move'] and ('specs/prsg-011-legacy/design-concept.md', 'specs/prsg-011-legacy/.process/design-concept.md') in [(i.get('source'), i.get('target')) for i in data['items'] if i.get('action') == 'move'] and ('specs/prsg-011-legacy/workflow.md', 'specs/prsg-011-legacy/.process/workflow.md') in [(i.get('source'), i.get('target')) for i in data['items'] if i.get('action') == 'move']" \
  "missing one or more root PROCESS allow-list move items"

set_test "dry-run does not move files outside the PROCESS allow-list"
json_check "$output" \
  "not any((i.get('source') == 'specs/prsg-011-legacy/notes.md') or (i.get('path') == 'specs/prsg-011-legacy/notes.md') or (i.get('target') == 'specs/prsg-011-legacy/.process/notes.md') for i in data['items'])" \
  "notes.md must not be classified as PROCESS"

set_test "dry-run includes review packet canonicalization"
json_check "$output" \
  "any(i.get('action') == 'move' and i.get('source') == 'specs/prsg-011-legacy/peer-review-round1.md' and i.get('target') == 'specs/prsg-011-legacy/.process/pr-review-packet.md' for i in data['items'])" \
  "missing peer-review to pr-review-packet move item"

set_test "dry-run includes evidence normalization"
json_check "$output" \
  "any(i.get('action') == 'normalize' and i.get('source') == 'specs/prsg-011-legacy/evidence/verification-evidence.md' and i.get('target') == 'specs/prsg-011-legacy/.process/evidence/verification-evidence.md' for i in data['items'])" \
  "missing evidence normalization item"

set_test "dry-run includes docs-side PROCESS anchor move"
json_check "$output" \
  "any(i.get('action') == 'move' and i.get('source') == 'docs/ai/specs/prsg-011-legacy-design-concept.md' and i.get('target') == 'docs/ai/specs/.process/prsg-011-legacy-design-concept.md' for i in data['items'])" \
  "missing docs-side design-concept move item"

set_test "dry-run includes docs-side workflow PROCESS anchor move"
json_check "$output" \
  "any(i.get('action') == 'move' and i.get('source') == 'docs/ai/specs/prsg-011-legacy-workflow.md' and i.get('target') == 'docs/ai/specs/.process/prsg-011-legacy-workflow.md' for i in data['items'])" \
  "missing docs-side workflow move item"

set_test "dry-run ignores deferred PRSG-001 scaffold artifacts for the PRSG-011 target"
json_check "$output" \
  "not any('PRSG-001-' in (i.get('source') or i.get('path') or i.get('target') or '') for i in data['items'])" \
  "PRSG-001 deferred scaffold artifacts must not be moved for PRSG-011"

set_test "dry-run protects visible CONTRACT artifacts"
json_check "$output" \
  "any(i.get('action') == 'protected_contract' and i.get('path') == 'specs/prsg-011-legacy/spec.md' for i in data['items'])" \
  "missing CONTRACT protection item"

set_test "dry-run protects all CONTRACT artifacts, including allow-list-like names under CONTRACT dirs"
json_check "$output" \
  "'specs/prsg-011-legacy/SPEC-MOC.md' in [i.get('path') for i in data['items'] if i.get('action') == 'protected_contract'] and 'specs/prsg-011-legacy/spec.md' in [i.get('path') for i in data['items'] if i.get('action') == 'protected_contract'] and 'specs/prsg-011-legacy/plan.md' in [i.get('path') for i in data['items'] if i.get('action') == 'protected_contract'] and 'specs/prsg-011-legacy/tasks.md' in [i.get('path') for i in data['items'] if i.get('action') == 'protected_contract'] and 'specs/prsg-011-legacy/research.md' in [i.get('path') for i in data['items'] if i.get('action') == 'protected_contract'] and 'specs/prsg-011-legacy/data-model.md' in [i.get('path') for i in data['items'] if i.get('action') == 'protected_contract'] and 'specs/prsg-011-legacy/quickstart.md' in [i.get('path') for i in data['items'] if i.get('action') == 'protected_contract'] and 'specs/prsg-011-legacy/contracts/analysis.md' in [i.get('path') for i in data['items'] if i.get('action') == 'protected_contract'] and 'specs/prsg-011-legacy/checklists/cleanup-report.md' in [i.get('path') for i in data['items'] if i.get('action') == 'protected_contract']" \
  "missing one or more CONTRACT protection items"

set_test "dry-run reports already-normalized .process artifacts as no-op"
json_check "$output" \
  "any(i.get('action') == 'noop_current' and i.get('path') == 'specs/prsg-011-legacy/.process/uat-runbook.md' for i in data['items'])" \
  "missing already-normalized no-op item"

set_test "dry-run reports additional already-normalized .process artifacts as no-op"
json_check "$output" \
  "any(i.get('action') == 'noop_current' and i.get('path') == 'specs/prsg-011-legacy/.process/existing-report.md' for i in data['items'])" \
  "missing already-normalized report no-op item"

set_test "dry-run includes stamp and generated-update decisions"
json_check "$output" \
  "any(i.get('action') == 'stamp' for i in data['items']) and any(i.get('action') == 'generated_update' for i in data['items'])" \
  "missing stamp or generated-update item"

set_test "dry-run leaves the worktree clean"
assert_eq "" "$(git -C "$repo" status --porcelain=v1 --untracked-files=all)" "git status after dry-run"

section "apply backup override and relocation effects"

apply_backup_root="$FIXTURE_DIR/backups-apply"
apply_stamp="20260608T010203Z"
apply_expected_backup="$apply_backup_root/speckit-migration-backup-$apply_stamp"

set_test "apply exits 0 on a clean relocatable spec"
result=0
run_relocator apply_output apply_stderr \
  env SPECKIT_MIGRATION_BACKUP_ROOT="$apply_backup_root" SPECKIT_MIGRATION_BACKUP_STAMP="$apply_stamp" \
  "$SCRIPT" --apply --spec specs/prsg-011-legacy --repo-root "$repo" || result=$?
assert_eq "0" "$result" "exit code"

set_test "apply emits one compact JSON object"
assert_compact_json_object "$apply_output"

set_test "apply report records applied status"
assert_json_field "$apply_output" "status" "applied"

set_test "apply report records created backup"
assert_json_field "$apply_output" "backup.created" "True"

set_test "apply uses deterministic backup override path"
assert_json_field "$apply_output" "backup.path" "$apply_expected_backup"

set_test "apply creates the deterministic backup directory"
assert_dir_exists "$apply_expected_backup"

set_test "apply itemizes backup creation"
json_check "$apply_output" \
  "data['backup']['path'] in [i.get('path') for i in data['items'] if i.get('action') == 'backup']" \
  "missing backup item"

set_test "apply moves spec-root PROCESS artifact"
assert_file_exists "$repo/specs/prsg-011-legacy/.process/retrospective.md"

set_test "apply removes relocated root PROCESS artifact"
assert_file_not_exists "$repo/specs/prsg-011-legacy/retrospective.md"

set_test "apply moves the root PROCESS allow-list families"
for moved_path in \
  analysis.md \
  cleanup-report.md \
  incident-report.md \
  uat-notes.md \
  design-concept.md \
  workflow.md
do
  assert_file_exists "$repo/specs/prsg-011-legacy/.process/$moved_path"
done

set_test "apply leaves files outside the PROCESS allow-list in place"
assert_file_exists "$repo/specs/prsg-011-legacy/notes.md"

set_test "apply canonicalizes review packet"
assert_file_exists "$repo/specs/prsg-011-legacy/.process/pr-review-packet.md"

set_test "apply removes legacy review packet source after canonicalization"
assert_file_not_exists "$repo/specs/prsg-011-legacy/peer-review-round1.md"

set_test "apply normalizes verification evidence"
assert_file_exists "$repo/specs/prsg-011-legacy/.process/evidence/verification-evidence.md"

set_test "apply removes root evidence source after normalization"
assert_file_not_exists "$repo/specs/prsg-011-legacy/evidence/verification-evidence.md"

set_test "apply preserves unrelated evidence files under the canonical evidence anchor"
assert_file_exists "$repo/specs/prsg-011-legacy/.process/evidence/supporting-note.md"

set_test "apply moves matching docs-side PROCESS artifact"
assert_file_exists "$repo/docs/ai/specs/.process/prsg-011-legacy-design-concept.md"

set_test "apply removes relocated docs-side design source"
assert_file_not_exists "$repo/docs/ai/specs/prsg-011-legacy-design-concept.md"

set_test "apply moves matching docs-side workflow artifact"
assert_file_exists "$repo/docs/ai/specs/.process/prsg-011-legacy-workflow.md"

set_test "apply removes relocated docs-side workflow source"
assert_file_not_exists "$repo/docs/ai/specs/prsg-011-legacy-workflow.md"

set_test "apply leaves unrelated docs-side roadmap visible"
assert_file_exists "$repo/docs/ai/specs/pr-size-governance-technical-roadmap.md"

set_test "apply leaves deferred PRSG-001 scaffold design artifact visible"
assert_file_exists "$repo/docs/ai/specs/PRSG-001-design-concept.md"

set_test "apply leaves deferred PRSG-001 scaffold workflow artifact visible"
assert_file_exists "$repo/docs/ai/specs/PRSG-001-workflow.md"

set_test "apply does not create deferred PRSG-001 .process targets"
assert_file_not_exists "$repo/docs/ai/specs/.process/PRSG-001-design-concept.md"

set_test "apply preserves CONTRACT artifact at spec root"
assert_file_exists "$repo/specs/prsg-011-legacy/spec.md"

set_test "apply preserves PROCESS-like names under CONTRACT directories"
assert_file_exists "$repo/specs/prsg-011-legacy/contracts/analysis.md"

set_test "apply stamps SPEC-MOC with structureVersion"
assert_contains "$(cat "$repo/specs/prsg-011-legacy/SPEC-MOC.md")" "structureVersion: 1"

section "already-current idempotency"

idempotent_backup_root="$FIXTURE_DIR/backups-idempotent"
idempotent_stamp="20260608T020304Z"
idempotent_expected_backup="$idempotent_backup_root/speckit-migration-backup-$idempotent_stamp"

set_test "repeat apply exits 0 on already-current relocation"
result=0
run_relocator idempotent_output idempotent_stderr \
  env SPECKIT_MIGRATION_BACKUP_ROOT="$idempotent_backup_root" SPECKIT_MIGRATION_BACKUP_STAMP="$idempotent_stamp" \
  "$SCRIPT" --apply --spec specs/prsg-011-legacy --repo-root "$repo" || result=$?
assert_eq "0" "$result" "exit code"

set_test "repeat apply reports noop"
assert_json_field "$idempotent_output" "status" "noop"

set_test "repeat apply does not create another backup"
assert_json_field "$idempotent_output" "backup.created" "False"

set_test "repeat apply leaves deterministic backup path absent"
assert_file_not_exists "$idempotent_expected_backup"

set_test "repeat apply reports current-state no-op items"
json_check "$idempotent_output" \
  "any(i.get('action') == 'noop_current' and i.get('path') == 'specs/prsg-011-legacy/.process/retrospective.md' for i in data['items'])" \
  "missing no-op current-state item after relocation"

set_test "repeat apply does not emit mutation items"
json_check "$idempotent_output" \
  "not any(i.get('action') in ['move', 'normalize', 'stamp', 'generated_update', 'backup'] for i in data['items'])" \
  "already-current apply must not emit mutation items"

section "missing SPEC-MOC blocks relocation"

missing_repo="$FIXTURE_DIR/repo-missing-moc"
mkdir -p "$missing_repo"
make_relocation_repo "$missing_repo"
git -C "$missing_repo" rm -q specs/prsg-011-legacy/SPEC-MOC.md
commit_fixture_change "$missing_repo" "remove SPEC-MOC marker"
missing_backup_root="$FIXTURE_DIR/backups-missing-moc"
missing_stamp="20260608T030405Z"
missing_expected_backup="$missing_backup_root/speckit-migration-backup-$missing_stamp"

set_test "missing SPEC-MOC dry-run exits 2"
result=0
run_relocator missing_output missing_stderr \
  env SPECKIT_MIGRATION_BACKUP_ROOT="$missing_backup_root" SPECKIT_MIGRATION_BACKUP_STAMP="$missing_stamp" \
  "$SCRIPT" --dry-run --spec specs/prsg-011-legacy --repo-root "$missing_repo" || result=$?
assert_eq "2" "$result" "exit code"

set_test "missing SPEC-MOC reports blocked_missing_moc"
assert_json_field "$missing_output" "status" "blocked_missing_moc"

set_test "missing SPEC-MOC does not create backup"
assert_json_field "$missing_output" "backup.created" "False"

set_test "missing SPEC-MOC leaves backup path absent"
assert_file_not_exists "$missing_expected_backup"

section "target collision pre-mutation blocks"

review_collision_repo="$FIXTURE_DIR/repo-review-collision"
mkdir -p "$review_collision_repo"
make_relocation_repo "$review_collision_repo"
printf '# Canonical Review Packet\n' > "$review_collision_repo/specs/prsg-011-legacy/pr-review-packet.md"
commit_fixture_change "$review_collision_repo" "add competing review packet source"
review_collision_backup_root="$FIXTURE_DIR/backups-review-collision"
review_collision_stamp="20260608T050607Z"
review_collision_expected_backup="$review_collision_backup_root/speckit-migration-backup-$review_collision_stamp"

set_test "review-packet collision dry-run exits 0"
result=0
run_relocator review_collision_dry_output review_collision_dry_stderr \
  env SPECKIT_MIGRATION_BACKUP_ROOT="$review_collision_backup_root" SPECKIT_MIGRATION_BACKUP_STAMP="$review_collision_stamp" \
  "$SCRIPT" --dry-run --spec specs/prsg-011-legacy --repo-root "$review_collision_repo" || result=$?
assert_eq "0" "$result" "exit code"

set_test "review-packet collision dry-run reports blocked_collision"
assert_json_field "$review_collision_dry_output" "status" "blocked_collision"

set_test "review-packet collision item targets canonical review packet"
json_check "$review_collision_dry_output" \
  "any(i.get('action') == 'collision' and i.get('target') == 'specs/prsg-011-legacy/.process/pr-review-packet.md' for i in data['items'])" \
  "missing review-packet collision item"

set_test "review-packet collision apply exits 2"
result=0
run_relocator review_collision_apply_output review_collision_apply_stderr \
  env SPECKIT_MIGRATION_BACKUP_ROOT="$review_collision_backup_root" SPECKIT_MIGRATION_BACKUP_STAMP="$review_collision_stamp" \
  "$SCRIPT" --apply --spec specs/prsg-011-legacy --repo-root "$review_collision_repo" || result=$?
assert_eq "2" "$result" "exit code"

set_test "review-packet collision apply does not create backup"
assert_json_field "$review_collision_apply_output" "backup.created" "False"

set_test "review-packet collision leaves backup path absent"
assert_file_not_exists "$review_collision_expected_backup"

set_test "review-packet collision leaves source files unmoved"
assert_file_exists "$review_collision_repo/specs/prsg-011-legacy/pr-review-packet.md"

evidence_collision_repo="$FIXTURE_DIR/repo-evidence-collision"
mkdir -p "$evidence_collision_repo"
make_relocation_repo "$evidence_collision_repo"
printf 'root evidence candidate\n' > "$evidence_collision_repo/specs/prsg-011-legacy/verification-evidence.md"
commit_fixture_change "$evidence_collision_repo" "add competing evidence source"
evidence_collision_backup_root="$FIXTURE_DIR/backups-evidence-collision"
evidence_collision_stamp="20260608T060708Z"
evidence_collision_expected_backup="$evidence_collision_backup_root/speckit-migration-backup-$evidence_collision_stamp"

set_test "evidence collision apply exits 2"
result=0
run_relocator evidence_collision_output evidence_collision_stderr \
  env SPECKIT_MIGRATION_BACKUP_ROOT="$evidence_collision_backup_root" SPECKIT_MIGRATION_BACKUP_STAMP="$evidence_collision_stamp" \
  "$SCRIPT" --apply --spec specs/prsg-011-legacy --repo-root "$evidence_collision_repo" || result=$?
assert_eq "2" "$result" "exit code"

set_test "evidence collision reports blocked_collision"
assert_json_field "$evidence_collision_output" "status" "blocked_collision"

set_test "evidence collision item targets canonical verification evidence"
json_check "$evidence_collision_output" \
  "any(i.get('action') == 'collision' and i.get('target') == 'specs/prsg-011-legacy/.process/evidence/verification-evidence.md' for i in data['items'])" \
  "missing evidence collision item"

set_test "evidence collision does not create backup"
assert_json_field "$evidence_collision_output" "backup.created" "False"

set_test "evidence collision leaves backup path absent"
assert_file_not_exists "$evidence_collision_expected_backup"

section "frozen in-flight and out-of-scope targets"

frozen_repo="$FIXTURE_DIR/repo-frozen"
mkdir -p "$frozen_repo/.specify"
make_relocation_repo "$frozen_repo"
cat > "$frozen_repo/.specify/feature.json" <<'EOF'
{"feature_directory":"specs/prsg-011-legacy"}
EOF
commit_fixture_change "$frozen_repo" "mark target spec in-flight"
frozen_backup_root="$FIXTURE_DIR/backups-frozen"
frozen_stamp="20260608T070809Z"
frozen_expected_backup="$frozen_backup_root/speckit-migration-backup-$frozen_stamp"

set_test "frozen in-flight apply exits 0 as safe no-op"
result=0
run_relocator frozen_output frozen_stderr \
  env SPECKIT_MIGRATION_BACKUP_ROOT="$frozen_backup_root" SPECKIT_MIGRATION_BACKUP_STAMP="$frozen_stamp" \
  "$SCRIPT" --apply --spec specs/prsg-011-legacy --repo-root "$frozen_repo" || result=$?
assert_eq "0" "$result" "exit code"

set_test "frozen in-flight report records active feature"
assert_json_field "$frozen_output" "active_feature.state" "valid"

set_test "frozen in-flight report itemizes skip"
json_check "$frozen_output" \
  "any(i.get('action') == 'skipped_frozen_in_flight' and (i.get('path') == 'specs/prsg-011-legacy' or i.get('target') == 'specs/prsg-011-legacy') for i in data['items'])" \
  "missing skipped_frozen_in_flight item"

set_test "frozen in-flight apply creates no backup"
assert_json_field "$frozen_output" "backup.created" "False"

set_test "frozen in-flight leaves backup path absent"
assert_file_not_exists "$frozen_expected_backup"

set_test "frozen in-flight leaves PROCESS source unmoved"
assert_file_exists "$frozen_repo/specs/prsg-011-legacy/retrospective.md"

out_scope_repo="$FIXTURE_DIR/repo-out-of-scope"
mkdir -p "$out_scope_repo"
make_relocation_repo "$out_scope_repo"
mv "$out_scope_repo/specs/prsg-011-legacy" "$out_scope_repo/specs/team-011-legacy"
commit_fixture_change "$out_scope_repo" "rename spec to non-SpecKit namespace"

set_test "non-SpecKit namespace dry-run exits 0"
result=0
run_relocator out_scope_output out_scope_stderr \
  "$SCRIPT" --dry-run --spec specs/team-011-legacy --repo-root "$out_scope_repo" || result=$?
assert_eq "0" "$result" "exit code"

set_test "non-SpecKit namespace reports skipped_out_of_scope"
json_check "$out_scope_output" \
  "any(i.get('action') == 'skipped_out_of_scope' and i.get('reason') == 'non_speckit_namespace' and (i.get('path') == 'specs/team-011-legacy' or i.get('target') == 'specs/team-011-legacy') for i in data['items'])" \
  "missing non-SpecKit out-of-scope item"

set_test "non-SpecKit namespace emits no relocation candidates"
json_check "$out_scope_output" \
  "not any(i.get('action') in ['move', 'normalize', 'protected_contract', 'stamp', 'generated_update', 'collision'] for i in data['items'])" \
  "out-of-scope target must not emit Tier-2 relocation candidates"

date_scope_repo="$FIXTURE_DIR/repo-date-out-of-scope"
mkdir -p "$date_scope_repo"
make_relocation_repo "$date_scope_repo"
mv "$date_scope_repo/specs/prsg-011-legacy" "$date_scope_repo/specs/2026-06-08-legacy"
commit_fixture_change "$date_scope_repo" "rename spec to date-first namespace"

set_test "date-first namespace dry-run exits 0"
result=0
run_relocator date_scope_output date_scope_stderr \
  "$SCRIPT" --dry-run --spec specs/2026-06-08-legacy --repo-root "$date_scope_repo" || result=$?
assert_eq "0" "$result" "exit code"

set_test "date-first namespace reports skipped_out_of_scope"
json_check "$date_scope_output" \
  "any(i.get('action') == 'skipped_out_of_scope' and i.get('reason') == 'date_named_legacy_namespace' and (i.get('path') == 'specs/2026-06-08-legacy' or i.get('target') == 'specs/2026-06-08-legacy') for i in data['items'])" \
  "missing date-first out-of-scope item"

section "dirty apply blocks before backup or mutation"

dirty_repo="$FIXTURE_DIR/repo-dirty"
mkdir -p "$dirty_repo"
make_relocation_repo "$dirty_repo"
printf 'dirty local edit\n' >> "$dirty_repo/specs/prsg-011-legacy/spec.md"
dirty_backup_root="$FIXTURE_DIR/backups-dirty"
dirty_stamp="20260608T040506Z"
dirty_expected_backup="$dirty_backup_root/speckit-migration-backup-$dirty_stamp"

set_test "dirty apply exits 2"
result=0
run_relocator dirty_output dirty_stderr \
  env SPECKIT_MIGRATION_BACKUP_ROOT="$dirty_backup_root" SPECKIT_MIGRATION_BACKUP_STAMP="$dirty_stamp" \
  "$SCRIPT" --apply --spec specs/prsg-011-legacy --repo-root "$dirty_repo" || result=$?
assert_eq "2" "$result" "exit code"

set_test "dirty apply reports blocked_dirty_tree"
assert_json_field "$dirty_output" "status" "blocked_dirty_tree"

set_test "dirty apply reports dirty tree"
assert_json_field "$dirty_output" "dirty_tree.is_dirty" "True"

set_test "dirty apply reports apply_blocked"
assert_json_field "$dirty_output" "dirty_tree.apply_blocked" "True"

set_test "dirty apply does not create backup"
assert_json_field "$dirty_output" "backup.created" "False"

set_test "dirty apply keeps deterministic backup path planned"
assert_json_field "$dirty_output" "backup.path" "$dirty_expected_backup"

set_test "dirty apply leaves backup path absent"
assert_file_not_exists "$dirty_expected_backup"

set_test "dirty apply leaves root PROCESS artifact unmoved"
assert_file_exists "$dirty_repo/specs/prsg-011-legacy/retrospective.md"

set_test "dirty apply leaves target PROCESS artifact absent"
assert_file_not_exists "$dirty_repo/specs/prsg-011-legacy/.process/retrospective.md"

test_summary
