#!/usr/bin/env bash
# test-migrate-structure.sh - RED scaffold for PRSG-011 repository migration
#
# This file intentionally starts RED: migrate-structure.sh does not exist yet.
# The guard below must fail cleanly until T008 adds the implementation. The
# fixture still encodes the helper-reuse contract for T001:
#   - active-feature freezing must use shared moc_id_match semantics
#     (PRSG-013A never freezes PRSG-013A1).
#   - repo structure marker gating must use shared moc_is_gated /
#     moc_frontmatter_field semantics (quoted or missing version stays legacy).

set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=../lib/assertions.sh
source "$HERE/../lib/assertions.sh"
# shellcheck source=../../../speckit-pro/skills/speckit-autopilot/scripts/lib/moc-id-normalize.sh
source "$HERE/../../../speckit-pro/skills/speckit-autopilot/scripts/lib/moc-id-normalize.sh"
# shellcheck source=../../../speckit-pro/skills/speckit-autopilot/scripts/lib/moc-frontmatter.sh
source "$HERE/../../../speckit-pro/skills/speckit-autopilot/scripts/lib/moc-frontmatter.sh"

MIGRATE="$HERE/../../../speckit-pro/skills/speckit-autopilot/scripts/migrate-structure.sh"
PROCESS_RULE='**/.process/** linguist-generated=true'

WORK="$(mktemp -d "${TMPDIR:-/tmp}/migrate-structure-l4.XXXXXX")"
trap 'rm -rf "$WORK"' EXIT

json_field() {
  local json="$1" field="$2"
  printf '%s' "$json" | python3 -c "
import json, sys
try:
    data = json.load(sys.stdin)
    value = data
    for part in '$field'.split('.'):
        value = value[part]
    print(value)
except Exception:
    print('__parse_error__')
" 2>/dev/null || printf '__parse_error__'
}

json_has_item() {
  local json="$1" action="$2" path="$3" reason="${4:-}"
  printf '%s' "$json" | python3 -c "
import json, sys
try:
    data = json.load(sys.stdin)
except Exception:
    sys.exit(1)
for item in data.get('items', []):
    if item.get('action') != '$action':
        continue
    pathish = item.get('path', item.get('target', item.get('id', '')))
    if pathish != '$path':
        continue
    if '$reason' and item.get('reason') != '$reason':
        continue
    sys.exit(0)
sys.exit(1)
" 2>/dev/null
}

json_check() {
  local json="$1" expr="$2" msg="$3"
  local file="$WORK/json-check.$RANDOM.json"
  printf '%s' "$json" > "$file"
  if python3 - "$file" "$expr" >/dev/null 2>&1 <<'PY'
import json
import sys

with open(sys.argv[1], encoding="utf-8") as fh:
    data = json.load(fh)

expr = sys.argv[2]
safe_builtins = {"any": any, "all": all, "len": len, "list": list, "sorted": sorted, "str": str}
if not eval(expr, {"__builtins__": safe_builtins}, {"data": data}):
    raise SystemExit(1)
PY
  then
    _pass
  else
    _fail "$msg"
  fi
}

assert_dir_exists() {
  local path="$1" msg="${2:-}"
  if [ -d "$path" ]; then
    _pass
  else
    _fail "${msg:+$msg: }directory not found: $path"
  fi
}

assert_dir_not_exists() {
  local path="$1" msg="${2:-}"
  if [ ! -d "$path" ]; then
    _pass
  else
    _fail "${msg:+$msg: }directory should not exist: $path"
  fi
}

run_migrate() {
  local __var="$1" __want="$2"
  shift 2
  local __out __rc=0
  __out="$("$MIGRATE" "$@" 2>&1)" || __rc=$?
  printf -v "$__var" '%s' "$__out"
  assert_eq "$__want" "$__rc" "exit code for: migrate-structure.sh $*"
}

make_repo_fixture() {
  local repo="$1"
  mkdir -p "$repo"
  git -C "$repo" init -q
  git -C "$repo" config user.email support@openai.com
  git -C "$repo" config user.name Test
  git -C "$repo" config commit.gpgsign false
  mkdir -p "$repo/.specify" "$repo/docs/ai/specs" "$repo/specs" \
    "$repo/speckit-pro/skills/speckit-autopilot/scripts" \
    "$repo/speckit-pro/skills/speckit-coach/templates"

  cat > "$repo/docs/ai/specs/pr-size-governance-roadmap-MOC.md" <<'EOF'
---
up: "[root](README.md)"
related: []
status: ""
rank:
spec_id: PRSG
structureVersion: 1
---
# PR Size Governance Roadmap

<!-- GENERATED:INDEX:START (do not edit; regenerated by generate-spec-index.sh) -->
<!-- GENERATED:INDEX:END -->
EOF

  cat > "$repo/docs/ai/specs/pr-size-governance-technical-roadmap.md" <<'EOF'
# PR Size Governance Technical Roadmap

Legacy split exception wording should be removed from live project roadmaps.
Legacy transition exception wording should be removed from live project roadmaps.
Legacy ratified exception wording should be removed from live project roadmaps.
EOF

  cat > "$repo/speckit-pro/skills/speckit-coach/templates/roadmap-moc-template.md" <<'EOF'
# Template Roadmap

Template split exception wording is not a live-project roadmap migration target.
EOF

  cat > "$repo/speckit-pro/skills/speckit-autopilot/scripts/reviewability-gate.sh" <<'EOF'
#!/usr/bin/env bash
# Fixture sentinel: migrate-structure must not teach the gate to parse .gitattributes.
echo reviewability-gate-fixture
EOF
  chmod +x "$repo/speckit-pro/skills/speckit-autopilot/scripts/reviewability-gate.sh"

  cat > "$repo/.specify/feature.json" <<'EOF'
{"feature_directory":"specs/prsg-013a-active"}
EOF

  mkdir -p "$repo/.specify/memory"
  cat > "$repo/.specify/memory/spec.md" <<'EOF'
# Archived Spec Memory

## PRSG-016 Archived Memory

Archived PRSG spec that has no on-disk spec directory.

## team-017 Archived Team Note

Non-SpecKit archive-memory note that must not receive a generated row.

## 2026-06-08 Archived Daily Note

Date-named legacy archive-memory note that must stay out of scope.
EOF

  mkdir -p "$repo/specs/prsg-013a-active"
  cat > "$repo/specs/prsg-013a-active/spec.md" <<'EOF'
# Active PRSG-013A
EOF

  mkdir -p "$repo/specs/prsg-013a1-helper-reuse"
  cat > "$repo/specs/prsg-013a1-helper-reuse/spec.md" <<'EOF'
# Completed PRSG-013A1

This completed legacy spec is intentionally near-miss named with PRSG-013A.
The migration must rely on moc_id_match's opaque whole-segment comparison so
PRSG-013A does not freeze PRSG-013A1.
EOF

  mkdir -p "$repo/specs/prsg-015-gated-current"
  cat > "$repo/specs/prsg-015-gated-current/SPEC-MOC.md" <<'EOF'
---
up: "[roadmap](../../docs/ai/specs/pr-size-governance-roadmap-MOC.md)"
related: []
status: complete
rank:
spec_id: PRSG-015
structureVersion: 1
---
# PRSG-015

<!-- GENERATED:INDEX:START (do not edit; regenerated by generate-spec-index.sh) -->
<!-- GENERATED:INDEX:END -->
EOF

  mkdir -p "$repo/specs/prsg-014-quoted-version"
  cat > "$repo/specs/prsg-014-quoted-version/SPEC-MOC.md" <<'EOF'
---
up: "[roadmap](../../docs/ai/specs/pr-size-governance-roadmap-MOC.md)"
related: []
status: complete
rank:
spec_id: PRSG-014
structureVersion: "1"
---
# PRSG-014

Quoted structureVersion must stay non-gated per moc-frontmatter.sh.
EOF

  mkdir -p "$repo/specs/team-015-not-speckit"
  cat > "$repo/specs/team-015-not-speckit/spec.md" <<'EOF'
# Team-owned note
EOF

  mkdir -p "$repo/specs/2026-06-08-not-speckit"
  cat > "$repo/specs/2026-06-08-not-speckit/spec.md" <<'EOF'
# Date-named legacy note
EOF

  git -C "$repo" add .
  git -C "$repo" commit -qm "seed migrate-structure fixture"
}

make_invalid_active_fixture() {
  local repo="$1" variant="$2"
  make_repo_fixture "$repo"

  case "$variant" in
    malformed_json)
      printf '{"feature_directory":' > "$repo/.specify/feature.json"
      ;;
    missing_key)
      printf '{"other":"specs/prsg-013a-active"}\n' > "$repo/.specify/feature.json"
      ;;
    non_string)
      printf '{"feature_directory":42}\n' > "$repo/.specify/feature.json"
      ;;
    empty_string)
      printf '{"feature_directory":""}\n' > "$repo/.specify/feature.json"
      ;;
    outside_repo)
      printf '{"feature_directory":"../outside-repo"}\n' > "$repo/.specify/feature.json"
      ;;
    *)
      printf 'unknown invalid active-feature variant: %s\n' "$variant" >&2
      return 2
      ;;
  esac

  git -C "$repo" add .specify/feature.json
  git -C "$repo" commit -qm "seed invalid active-feature fixture"
}

snapshot_files() {
  local root="$1"
  (cd "$root" && find . -type f ! -path './.git/*' -print0 | LC_ALL=C sort -z | xargs -0 shasum)
}

# ---------------------------------------------------------------------------
section "RED guard - repository migration script must exist and be executable"
# ---------------------------------------------------------------------------

set_test "migrate-structure.sh exists at the contracted path"
assert_file_exists "$MIGRATE" "FAIL: repository migration script not found at $MIGRATE"

set_test "migrate-structure.sh is executable"
assert_file_executable "$MIGRATE" "FAIL: repository migration script not executable at $MIGRATE"

# ---------------------------------------------------------------------------
section "Fixture sanity - shared helpers define the expected edge behavior"
# ---------------------------------------------------------------------------

set_test "moc_id_match keeps PRSG-013A distinct from PRSG-013A1"
assert_exit_code 1 moc_id_match "PRSG-013A" "prsg-013a1-helper-reuse"

repo="$WORK/repo"
make_repo_fixture "$repo"

set_test "moc-frontmatter rejects quoted structureVersion as not gated"
assert_exit_code 1 moc_is_gated "$repo/specs/prsg-014-quoted-version/SPEC-MOC.md"

# ---------------------------------------------------------------------------
section "Dry-run scaffold - helper-sensitive migration decisions"
# ---------------------------------------------------------------------------

before="$(snapshot_files "$repo")"

set_test "dry-run over helper fixture exits 0"
run_migrate dry_out 0 --dry-run --repo-root "$repo"

after="$(snapshot_files "$repo")"
set_test "dry-run leaves the repository fixture byte-for-byte unchanged"
assert_eq "$before" "$after" "dry-run must be read-only"

set_test "dry-run emits migrate-structure report schema"
assert_eq "migrate-structure" "$(json_field "$dry_out" "script")"

set_test "dry-run reports pending repository marker work"
assert_eq "pending" "$(json_field "$dry_out" "status")"

set_test "active PRSG-013A is frozen using moc_id_match"
json_has_item "$dry_out" "skipped_frozen_in_flight" "specs/prsg-013a-active" && _pass || _fail "expected frozen item for active PRSG-013A"

set_test "near-miss PRSG-013A1 remains eligible, proving no prefix/truncated match"
json_has_item "$dry_out" "generated_update" "specs/prsg-013a1-helper-reuse/spec.md" && _pass || _fail "expected generated_update for PRSG-013A1 legacy target"

set_test "quoted structureVersion is treated as legacy via moc-frontmatter"
json_has_item "$dry_out" "generated_update" "specs/prsg-014-quoted-version/spec.md" && _pass || _fail "expected legacy spec.md target for quoted structureVersion"

set_test "non-SpecKit alpha namespace is skipped before normalization"
json_has_item "$dry_out" "skipped_out_of_scope" "specs/team-015-not-speckit" "non_speckit_namespace" && _pass || _fail "expected out-of-scope skip for non-SpecKit alpha namespace"

set_test "date-first legacy namespace is skipped before normalization"
json_has_item "$dry_out" "skipped_out_of_scope" "specs/2026-06-08-not-speckit" "date_named_legacy_namespace" && _pass || _fail "expected out-of-scope skip for date-named legacy namespace"

set_test "version-gated historical spec uses SPEC-MOC as durable target"
json_has_item "$dry_out" "generated_update" "specs/prsg-015-gated-current/SPEC-MOC.md" && _pass || _fail "expected generated_update for gated SPEC-MOC target"

set_test "archive-memory-only historical spec uses archive-memory section target"
json_check "$dry_out" \
  "any(i.get('action') == 'generated_update' and '.specify/memory/spec.md#prsg-016-archived-memory' in (i.get('path') or i.get('target') or i.get('id') or '') for i in data.get('items', []))" \
  "expected generated_update for archive-memory section target"

set_test "archive-memory non-SpecKit namespace is skipped before row rendering"
json_check "$dry_out" \
  "any(i.get('action') == 'skipped_out_of_scope' and i.get('reason') == 'non_speckit_namespace' and 'team-017' in (i.get('path') or i.get('target') or i.get('id') or '') for i in data.get('items', []))" \
  "expected non-SpecKit archive-memory skip"

set_test "archive-memory date-first namespace is skipped before row rendering"
json_check "$dry_out" \
  "any(i.get('action') == 'skipped_out_of_scope' and i.get('reason') == 'date_named_legacy_namespace' and '2026-06-08' in (i.get('path') or i.get('target') or i.get('id') or '') for i in data.get('items', []))" \
  "expected date-named archive-memory skip"

set_test "dry-run reports repo-root .gitattributes process collapse work"
json_check "$dry_out" \
  "any(i.get('action') == 'pending' and i.get('path') == '.gitattributes' and i.get('reason') == 'process_linguist_generated_rule' for i in data.get('items', []))" \
  "expected pending .gitattributes process collapse item"

set_test "dry-run keeps reviewability gate out of .gitattributes work"
json_check "$dry_out" \
  "all('reviewability-gate.sh' not in str(i) for i in data.get('items', []))" \
  "migration must not make reviewability logic parse .gitattributes"

set_test "dry-run reports live-project roadmap de-boilerplate work"
json_check "$dry_out" \
  "any(i.get('action') == 'pending' and i.get('path') == 'docs/ai/specs/pr-size-governance-technical-roadmap.md' and i.get('reason') == 'roadmap_deboilerplate' for i in data.get('items', []))" \
  "expected pending live-project roadmap de-boilerplate item"

# ---------------------------------------------------------------------------
section "Active feature invalid fixtures - dry-run reports and apply blocks"
# ---------------------------------------------------------------------------

for variant in malformed_json missing_key non_string empty_string outside_repo; do
  invalid_repo="$WORK/repo-invalid-$variant"
  make_invalid_active_fixture "$invalid_repo" "$variant"

  set_test "dry-run reports invalid active feature: $variant"
  run_migrate invalid_dry_out 0 --dry-run --repo-root "$invalid_repo"
  assert_eq "invalid" "$(json_field "$invalid_dry_out" "active_feature.state")" "active feature state"
done

invalid_apply_repo="$WORK/repo-invalid-apply"
make_invalid_active_fixture "$invalid_apply_repo" "malformed_json"
invalid_backup_root="$WORK/backups-invalid"
invalid_stamp="20260608T020304Z"
invalid_expected_backup="$invalid_backup_root/speckit-migration-backup-$invalid_stamp"

set_test "invalid active feature apply exits 2"
SPECKIT_MIGRATION_BACKUP_ROOT="$invalid_backup_root" SPECKIT_MIGRATION_BACKUP_STAMP="$invalid_stamp" \
  run_migrate invalid_apply_out 2 --apply --repo-root "$invalid_apply_repo"

set_test "invalid active feature apply reports blocked status"
assert_eq "blocked_active_feature_invalid" "$(json_field "$invalid_apply_out" "status")"

set_test "invalid active feature apply does not create backup"
assert_eq "False" "$(json_field "$invalid_apply_out" "backup.created")"

set_test "invalid active feature apply leaves planned backup absent"
assert_dir_not_exists "$invalid_expected_backup"

set_test "invalid active feature apply writes no structure marker"
assert_file_not_exists "$invalid_apply_repo/.specify/structure-version.json"

# ---------------------------------------------------------------------------
section "Dirty apply block - no backup or mutation before clean-tree check"
# ---------------------------------------------------------------------------

dirty_repo="$WORK/repo-dirty"
make_repo_fixture "$dirty_repo"
printf 'dirty local edit\n' >> "$dirty_repo/specs/prsg-013a1-helper-reuse/spec.md"
dirty_before="$(snapshot_files "$dirty_repo")"
dirty_backup_root="$WORK/backups-dirty"
dirty_stamp="20260608T040506Z"
dirty_expected_backup="$dirty_backup_root/speckit-migration-backup-$dirty_stamp"

set_test "dirty apply exits 2"
SPECKIT_MIGRATION_BACKUP_ROOT="$dirty_backup_root" SPECKIT_MIGRATION_BACKUP_STAMP="$dirty_stamp" \
  run_migrate dirty_out 2 --apply --repo-root "$dirty_repo"

set_test "dirty apply reports blocked_dirty_tree"
assert_eq "blocked_dirty_tree" "$(json_field "$dirty_out" "status")"

set_test "dirty apply reports dirty tree"
assert_eq "True" "$(json_field "$dirty_out" "dirty_tree.is_dirty")"

set_test "dirty apply reports apply-blocked dirty-tree state"
assert_eq "True" "$(json_field "$dirty_out" "dirty_tree.apply_blocked")"

set_test "dirty apply does not create backup"
assert_eq "False" "$(json_field "$dirty_out" "backup.created")"

set_test "dirty apply leaves planned backup absent"
assert_dir_not_exists "$dirty_expected_backup"

dirty_after="$(snapshot_files "$dirty_repo")"
set_test "dirty apply leaves the dirty fixture byte-for-byte unchanged"
assert_eq "$dirty_before" "$dirty_after" "dirty apply must block before mutation"

set_test "dirty apply writes no structure marker"
assert_file_not_exists "$dirty_repo/.specify/structure-version.json"

# ---------------------------------------------------------------------------
section "Apply - marker write, generated backfill, de-boilerplate, idempotency"
# ---------------------------------------------------------------------------

apply_repo="$WORK/repo-apply"
make_repo_fixture "$apply_repo"
apply_backup_root="$WORK/backups-apply"
apply_stamp="20260608T070809Z"
apply_expected_backup="$apply_backup_root/speckit-migration-backup-$apply_stamp"
gate_before="$(shasum "$apply_repo/speckit-pro/skills/speckit-autopilot/scripts/reviewability-gate.sh" | awk '{print $1}')"
template_before="$(shasum "$apply_repo/speckit-pro/skills/speckit-coach/templates/roadmap-moc-template.md" | awk '{print $1}')"

set_test "apply exits 0 on clean pending repository migration"
SPECKIT_MIGRATION_BACKUP_ROOT="$apply_backup_root" SPECKIT_MIGRATION_BACKUP_STAMP="$apply_stamp" \
  run_migrate apply_out 0 --apply --repo-root "$apply_repo"

set_test "apply reports applied status"
assert_eq "applied" "$(json_field "$apply_out" "status")"

set_test "apply creates deterministic backup"
assert_dir_exists "$apply_expected_backup"

set_test "apply reports created backup"
assert_eq "True" "$(json_field "$apply_out" "backup.created")"

set_test "apply itemizes backup creation"
json_check "$apply_out" \
  "data.get('backup', {}).get('path') in [i.get('path') for i in data.get('items', []) if i.get('action') == 'backup']" \
  "expected backup item in apply output"

set_test "apply writes repository structure marker"
assert_file_exists "$apply_repo/.specify/structure-version.json"

marker_json="$(cat "$apply_repo/.specify/structure-version.json" 2>/dev/null || true)"
set_test "repository structure marker records structureVersion 1"
assert_eq "1" "$(json_field "$marker_json" "structureVersion")"

set_test "apply ensures one repo-root .gitattributes process collapse rule"
assert_eq "1" "$(grep -cxF "$PROCESS_RULE" "$apply_repo/.gitattributes" 2>/dev/null || true)" "rule line count"

roadmap_after_apply="$(cat "$apply_repo/docs/ai/specs/pr-size-governance-roadmap-MOC.md" 2>/dev/null || true)"
set_test "generated backfill includes gated SPEC-MOC target"
assert_contains "$roadmap_after_apply" "../../../specs/prsg-015-gated-current/SPEC-MOC.md" "gated target row"

set_test "generated backfill includes legacy spec.md target"
assert_contains "$roadmap_after_apply" "../../../specs/prsg-013a1-helper-reuse/spec.md" "legacy target row"

set_test "generated backfill includes archive-memory target"
assert_contains "$roadmap_after_apply" "../../../.specify/memory/spec.md#prsg-016-archived-memory" "archive-memory target row"

set_test "generated backfill excludes active frozen PRSG-013A row"
assert_not_contains "$roadmap_after_apply" "../../../specs/prsg-013a-active/spec.md" "active feature must stay frozen"

set_test "generated backfill excludes non-SpecKit namespace row"
assert_not_contains "$roadmap_after_apply" "team-015-not-speckit" "non-SpecKit target must not be indexed"

set_test "generated backfill excludes date-first namespace row"
assert_not_contains "$roadmap_after_apply" "2026-06-08-not-speckit" "date-named target must not be indexed"

technical_roadmap_after="$(cat "$apply_repo/docs/ai/specs/pr-size-governance-technical-roadmap.md" 2>/dev/null || true)"
set_test "apply removes legacy split exception wording from live roadmap"
assert_not_contains "$technical_roadmap_after" "split exception" "live roadmap de-boilerplate"

set_test "apply removes legacy transition exception wording from live roadmap"
assert_not_contains "$technical_roadmap_after" "transition exception" "live roadmap de-boilerplate"

set_test "apply removes legacy ratified exception wording from live roadmap"
assert_not_contains "$technical_roadmap_after" "ratified exception" "live roadmap de-boilerplate"

gate_after="$(shasum "$apply_repo/speckit-pro/skills/speckit-autopilot/scripts/reviewability-gate.sh" 2>/dev/null | awk '{print $1}' || true)"
set_test "apply leaves reviewability gate byte-identical"
assert_eq "$gate_before" "$gate_after" "reviewability gate must not parse .gitattributes"

template_after="$(shasum "$apply_repo/speckit-pro/skills/speckit-coach/templates/roadmap-moc-template.md" 2>/dev/null | awk '{print $1}' || true)"
set_test "apply leaves plugin roadmap template byte-identical"
assert_eq "$template_before" "$template_after" "template roadmap boilerplate is out of scope"

after_first_apply="$(snapshot_files "$apply_repo")"
second_backup_root="$WORK/backups-apply-second"
second_stamp="20260608T101112Z"
second_expected_backup="$second_backup_root/speckit-migration-backup-$second_stamp"

set_test "second apply exits 0 on already-current repository"
SPECKIT_MIGRATION_BACKUP_ROOT="$second_backup_root" SPECKIT_MIGRATION_BACKUP_STAMP="$second_stamp" \
  run_migrate second_apply_out 0 --apply --repo-root "$apply_repo"

set_test "second apply reports noop current state"
assert_eq "noop" "$(json_field "$second_apply_out" "status")"

set_test "second apply reports backup not created"
assert_eq "False" "$(json_field "$second_apply_out" "backup.created")"

set_test "second apply leaves planned backup absent"
assert_dir_not_exists "$second_expected_backup"

set_test "second apply reports marker no-op current"
json_has_item "$second_apply_out" "noop_current" ".specify/structure-version.json" && _pass || _fail "expected marker noop_current item"

set_test "second apply reports generated navigation no-op current"
json_check "$second_apply_out" \
  "any(i.get('action') == 'noop_current' and 'GENERATED:INDEX' in (i.get('path') or i.get('target') or i.get('id') or i.get('reason') or '') for i in data.get('items', []))" \
  "expected generated navigation noop_current item"

after_second_apply="$(snapshot_files "$apply_repo")"
set_test "second apply is byte-for-byte idempotent"
assert_eq "$after_first_apply" "$after_second_apply" "idempotent apply must not mutate current repo"

test_summary
