// evaluate extension for pi. Generated by `evaluate setup pi` — do not edit by hand, as
// re-running that command overwrites this file.
//
// pi has no built-in MCP client, so this extension registers `evaluate` as a
// native pi tool and talks to the evaluate binary over MCP stdio. The tool schema and
// the TypeSafe request logic stay in one place: the Go server.
//
// ponytail: no automated test for the JSON-RPC client below; this repo is pure Go
// and tsc would mean a Node dev dependency for one file. `node --check` covers
// syntax, `pi -e cmd/evaluate/pi.ts` covers behaviour.

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent"
import { Type } from "typebox"
import { spawn } from "node:child_process"

const BINARY = __EVALUATE_BINARY__
const INSTRUCTIONS = __EVALUATE_INSTRUCTIONS__

const PROTOCOL_VERSION = "2025-06-18"

// callEvaluate runs one `evaluate` tool call against a fresh `evaluate mcp` process and
// resolves with the raw TypeSafe JSON.
//
// ponytail: one evaluate process per call; pool or keep one warm if latency shows up.
function callEvaluate(args: unknown, signal?: AbortSignal): Promise<string> {
  return new Promise<string>((resolve, reject) => {
    // addEventListener does not replay an abort that already happened, so an
    // aborted call would otherwise spawn evaluate and bill a request nobody wants.
    if (signal?.aborted) {
      reject(new Error("evaluate: aborted"))
      return
    }
    const child = spawn(BINARY, ["mcp"], { stdio: ["pipe", "pipe", "pipe"], env: process.env })

    let settled = false
    const finish = (err: Error | null, text?: string) => {
      // kill() below makes the child close with code null, which lands back here.
      if (settled) return
      settled = true
      signal?.removeEventListener("abort", onAbort)
      child.kill()
      if (err) reject(err)
      else resolve(text ?? "")
    }
    const onAbort = () => finish(new Error("evaluate: aborted"))
    signal?.addEventListener("abort", onAbort, { once: true })

    // A write error lands on the stream, not on the child, and an unhandled one
    // takes down the whole pi process. EPIPE only means evaluate exited first, and the
    // close handler below reports why, so it needs no message of its own.
    child.stdin.on("error", (err: NodeJS.ErrnoException) => {
      if (err.code !== "EPIPE") finish(err)
    })

    let stderr = ""
    child.stderr.setEncoding("utf8")
    child.stderr.on("data", (chunk: string) => {
      stderr += chunk
    })

    let buf = ""
    child.stdout.setEncoding("utf8")
    child.stdout.on("data", (chunk: string) => {
      buf += chunk
      // Newline-delimited JSON-RPC: keep any trailing partial line buffered.
      const lines = buf.split("\n")
      buf = lines.pop() ?? ""
      for (const line of lines) {
        if (!line.trim()) continue
        let msg: any
        try {
          msg = JSON.parse(line)
        } catch {
          continue
        }
        if (msg.id !== 2) continue
        if (msg.error) {
          return finish(new Error(`evaluate: ${msg.error.message ?? JSON.stringify(msg.error)}`))
        }
        const text = (msg.result?.content ?? []).map((c: any) => c.text ?? "").join("")
        // Tool errors arrive as a result with isError set, not as a JSON-RPC error.
        if (msg.result?.isError) return finish(new Error(`evaluate: ${text || "evaluate failed"}`))
        return finish(null, text)
      }
    })

    child.on("error", (err: Error) => finish(new Error(`evaluate: cannot run ${BINARY}: ${err.message}`)))
    child.on("close", (code: number | null) => {
      // evaluate already prefixes its stderr with "evaluate:", so pass it through as-is.
      const detail = stderr.trim()
      finish(new Error(detail || `evaluate: exited with code ${code}`))
    })

    try {
      const send = (msg: unknown) => child.stdin.write(`${JSON.stringify(msg)}\n`)
      send({
        jsonrpc: "2.0",
        id: 1,
        method: "initialize",
        params: {
          protocolVersion: PROTOCOL_VERSION,
          capabilities: {},
          clientInfo: { name: "pi", version: "1" },
        },
      })
      send({ jsonrpc: "2.0", method: "notifications/initialized" })
      send({ jsonrpc: "2.0", id: 2, method: "tools/call", params: { name: "evaluate", arguments: args } })
      // stdin deliberately stays open: evaluate shuts down on EOF, and would do so
      // before flushing the reply.
    } catch (err) {
      finish(err instanceof Error ? err : new Error(String(err)))
    }
  })
}

export default function (pi: ExtensionAPI) {
  pi.registerTool({
    name: "evaluate",
    label: "Jev",
    description:
      "Jev is a fast structured-decision model: unstructured state in, typed answers " +
      "(noul, choice, score) with calibrated confidence out; 70-500ms, schema-enforced. " +
      "Use for classification, routing, scoring, extraction, branching, guardrails/judging, " +
      "and map-reduce over large data — wherever hand-written logic is too brittle or latency matters. " +
      "Not for prose, code, or free-form text: the answer space must be enumerable up front (max 255 options).",
    promptSnippet:
      "Classify, route, score, extract, or guard with Jev: typed answers and calibrated confidence to branch on, in 70-500ms, instead of parsing prose.",
    // filter: an empty INSTRUCTIONS must not inject a blank guideline.
    promptGuidelines: INSTRUCTIONS.split("\n").filter(Boolean),
    parameters: Type.Object({
      state: Type.Any({
        description: "content to judge: plain text, or a JSON object/array with named fields",
      }),
      questions: Type.Object(
        {},
        {
          description:
            "map of question id to question; answers come back under the same ids, which are not sent to the model",
          // Not Type.Record: that emits patternProperties, which some providers reject.
          additionalProperties: Type.Object({
            type: Type.String({
              description:
                "noul (probability a yes/no condition holds), choice (one option from the criteria map), or score (probability-weighted position on ordered criteria levels)",
            }),
            instructions: Type.Any({
              description:
                "the judgment to make, with its full meaning; a string, or an object/array for definitions, contrasts, and examples",
            }),
            criteria: Type.Optional(
              Type.Any({
                description:
                  'noul: optional {"true": ..., "false": ...} descriptions; choice (required): map of option to description or null; score (required): ordered array of at least 2 level descriptions',
              }),
            ),
          }),
        },
      ),
      model: Type.Optional(Type.String({ description: "model to use; default jev-latest" })),
    }),
    async execute(_toolCallId, params, signal) {
      return { content: [{ type: "text", text: await callEvaluate(params, signal) }], details: {} }
    },
  })
}
